### ISSUE TITLE
Cours nsi

### ISSUE THREAD

**Issue by Nizyi** [tidic84/JDOCopilot#16]
Bonjour,

J'ai constaté que d'après l'application , les cours de nsi commencés a la sonnerie.
Or , ils commencent 10 minutes plus tard voir plus.
Je pense donc qu'il faudrait modifier cette donné si possible.

Merci d'avoir lu,
Cordialement Tom.

**Comment by aweirdwhale** [comment]
Je suis pas sûr qu'il apprécie mais ce sera fait à la prochaine update :]
